sonar.projectKey=agenda-citas-semana7
sonar.projectName=Agenda de Citas - Semana 7 CI/CD
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/vendor/**,**/node_modules/**,**/*.min.js,app/index.html
sonar.host.url=http://localhost:9000
sonar.language=php
